name: treated
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_pdfview: ^1.2.5
  path_provider: ^2.0.11
  dio: ^5.3.2
  url_launcher: ^6.1.4
  carousel_slider: ^5.0.0
  http: ^0.13.5
  # http: ^1.1.0
  connectivity_plus: ^4.0.0
  file_picker: ^8.1.3
  cupertino_icons: ^1.0.6
  flutter_cube: ^0.1.1
  animated_text_kit: ^4.2.2
  lottie: ^2.6.0
  vector_math: ^2.1.4
  excel: ^2.0.1
  file_saver: ^0.2.14
  form_field_validator: ^1.1.0
  mysql_client: ^0.0.27

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/image.png
    - assets/dks.png
    - assets/eks.png
    - assets/gok.png
    - assets/rec.png
    - assets/PCB.jpg
    - assets/legislative.pdf
    - assets/Availabity.xlsx
    - assets/Legislative_Govt.pdf
    - assets/Apartments.xlsx
    - assets/UnderConstruction.xlsx
    - assets/water_conservation.json
    - assets/Availabity1.xlsx
    - assets/IISC.jpeg
    - assets/KSPCB.png
